name: neomutt
base: core20
adopt-info: neomutt
summary: NeoMutt is a command line mail reader (or MUA)
description: |
  Command line mail reader based on Mutt, with added features Neomutt supports
  all the features that are supported by Mutt, including POP and IMAP support,
  SSL encryption and SASL authentication, threading and GPG support.
 
  On the top of that, neomutt provides:
  * Notmuch: a mail indexing tools that provides advanced features such as
    full-text search, thread reconstruction and added features.
  * Color attachment headers using regex, just like mail bodies.
  * Custom rules for theming the mail index.
  * NNTP support.
  * Visual progress bar for slow operations.
  * Trash folder.

  The snap version of neomutt expects configuration files in

      ~/snap/neomutt/current

  The main configuration file, for example, has to be placed in

      ~/snap/neomutt/current/.neomuttrc

  Note that this directory is versioned and is backed up when the snap is
  removed (see https://snapcraft.io/docs/data-locations#heading--user).
website: https://neomutt.org
contact: https://github.com/nicolasbock/neomutt-snap/issues
license: Apache-2.0
issues: https://github.com/nicolasbock/neomutt-snap/issues
source-code: https://github.com/nicolasbock/neomutt-snap
grade: stable
confinement: strict

apps:
  neomutt:
    command: usr/bin/neomutt
    plugs:
      - home
      - network

parts:
  neomutt:
    after: [neomutt-test-files]
    plugin: dump
    source: https://github.com/neomutt/neomutt.git
    source-tag: '20220429'
    build-packages:
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme-dev
      - libgss-dev
      - libidn11-dev
      - libkrb5-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.3-dev
      - libncurses-dev
      - libnotmuch-dev
      - libqdbm-dev
      - libsasl2-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - tcl
      - xsltproc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"
    override-build: |
      set -e -u -x
      ./configure \
        --testing \
        --gpgme \
        --gnutls \
        --gss \
        --sasl \
        --ssl \
        --lua \
        --notmuch \
        --mixmaster \
        --bdb \
        --gdbm \
        --kyotocabinet \
        --lmdb \
        --qdbm \
        --tokyocabinet \
        --disable-doc \
        --prefix=/usr
      make
      NEOMUTT_TEST_DIR="$(readlink --canonicalize ${SNAPCRAFT_PART_BUILD}/../../neomutt-test-files/build)" \
        make test
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}
    stage-packages:
      - libassuan0
      - libgdbm6
      - libgmime-3.0-0
      - libgpgme11
      - libidn11
      - libkyotocabinet16v5
      - liblmdb0
      - liblua5.3-0
      - libnotmuch5
      - libqdbm14
      - libtalloc2
      - libtokyocabinet9
      - libxapian30
  neomutt-test-files:
    plugin: dump
    source: https://github.com/neomutt/neomutt-test-files.git
    source-commit: 'dc9fb32a701eb9dce4fda93c27da1d9b5be23231'
    override-build: |
      set -e -u -x
      export NEOMUTT_TEST_DIR="${SNAPCRAFT_PART_BUILD}/build"
      ./setup.sh
