name: neomutt-snap
base: core20
adopt-info: neomutt
summary: NeoMutt is a command line mail reader (or MUA)
description: |
  Command line mail reader based on Mutt, with added features Neomutt supports
  all the features that are supported by Mutt, including POP and IMAP support,
  SSL encryption and SASL authentication, threading and GPG support.
 
  On the top of that, neomutt provides:
  * Notmuch: a mail indexing tools that provides advanced features such as
    full-text search, thread reconstruction and added features.
  * Color attachment headers using regex, just like mail bodies.
  * Custom rules for theming the mail index.
  * NNTP support.
  * Visual progress bar for slow operations.
  * Trash folder.

  The snap version of neomutt expects configuration files in

      ~/snap/neomutt-snap/common
website: https://neomutt.org
contact: https://github.com/nicolasbock/neomutt-snap/issues
license: Apache-2.0
grade: stable
confinement: strict

apps:
  neomutt:
    command: usr/bin/neomutt
    plugs:
      - home

parts:
  neomutt:
    plugin: dump
    source: https://github.com/neomutt/neomutt.git
    source-tag: '20220415'
    build-packages:
      - gettext
      - libgnutls28-dev
      - libgpgme-dev
      - libgss-dev
      - libidn11-dev
      - libkrb5-dev
      - libncurses-dev
      - libsasl2-dev
      - libxml2-utils
      - tcl
      - xsltproc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"
    override-build: |
      set -e -u -x
      ./configure \
        --gpgme \
        --gnutls \
        --gss \
        --sasl \
        --ssl \
        --disable-doc \
        --prefix=/usr
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}
    stage-packages:
      - libassuan0
      - libgpgme11
      - libidn11
