name: neomutt-snap
base: core20
adopt-info: neomutt
summary: NeoMutt is a command line mail reader (or MUA)
description: |
  Command line mail reader based on Mutt, with added features Neomutt supports
  all the features that are supported by Mutt, including POP and IMAP support,
  SSL encryption and SASL authentication, threading and GPG support.
 
  On the top of that, neomutt provides:
  * Notmuch: a mail indexing tools that provides advanced features such as
    full-text search, thread reconstruction and added features.
  * Color attachment headers using regex, just like mail bodies.
  * Custom rules for theming the mail index.
  * NNTP support.
  * Visual progress bar for slow operations.
  * Trash folder.

  The snap version of neomutt expects configuration files in

      ~/snap/neomutt-snap/common

  The main configuration file for example is expected to be in

      ~/snap/neomutt-snap/common/.neomuttrc
website: https://neomutt.org
contact: https://github.com/nicolasbock/neomutt-snap/issues
license: Apache-2.0
grade: stable
confinement: strict

apps:
  neomutt:
    environment:
      HOME: ${SNAP_USER_COMMON}
    command: usr/bin/neomutt
    plugs:
      - home
      - network

parts:
  neomutt:
    after: [neomutt-test-files]
    plugin: dump
    source: https://github.com/neomutt/neomutt.git
    source-tag: '20220415'
    build-packages:
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme-dev
      - libgss-dev
      - libidn11-dev
      - libkrb5-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - libncurses-dev
      - libqdbm-dev
      - libsasl2-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - tcl
      - xsltproc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"
    override-build: |
      set -e -u -x
      ./configure \
        --testing \
        --gpgme \
        --gnutls \
        --gss \
        --sasl \
        --ssl \
        --bdb \
        --gdbm \
        --kyotocabinet \
        --lmdb \
        --qdbm \
        --tokyocabinet \
        --disable-doc \
        --prefix=/usr
      make
      NEOMUTT_TEST_DIR="/root/parts/neomutt-test-files/build" \
        make test
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}
    stage-packages:
      - libassuan0
      - libgdbm6
      - libgpgme11
      - libidn11
      - libkyotocabinet16v5
      - liblmdb0
      - libqdbm14
      - libtokyocabinet9
  neomutt-test-files:
    plugin: dump
    source: https://github.com/neomutt/neomutt-test-files.git
    source-commit: 'dc9fb32a701eb9dce4fda93c27da1d9b5be23231'
    override-build: |
      set -e -u -x
      export NEOMUTT_TEST_DIR="${SNAPCRAFT_PART_BUILD}/build"
      ./setup.sh
