name: neomutt-snap
base: core20
version: '20220415'
summary: NeoMutt is a command line mail reader (or MUA)
description: |
  Command line mail reader based on Mutt, with added features Neomutt supports
  all the features that are supported by Mutt, including POP and IMAP support,
  SSL encryption and SASL authentication, threading and GPG support.
 
  On the top of that, neomutt provides:
  * Notmuch: a mail indexing tools that provides advanced features such as
    full-text search, thread reconstruction and added features.
  * Color attachment headers using regex, just like mail bodies.
  * Custom rules for theming the mail index.
  * NNTP support.
  * Visual progress bar for slow operations.
  * Trash folder.
website: https://neomutt.org
contact: https://github.com/nicolasbock/neomutt-snap/issues
license: apache-2.0
grade: stable
confinement: strict

apps:
  neomutt:
    command: usr/bin/neomutt

parts:
  neomutt:
    plugin: dump
    source: https://github.com/neomutt/neomutt.git
    source-tag: '20220415'
    build-packages:
      - libidn11-dev
      - libncurses-dev
      - libxml2-utils
      - gettext
      - tcl
      - xsltproc
    override-build: |
      set -e -u -x
      ./configure --disable-doc --prefix=/usr
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}
    stage-packages:
      - libidn11
