name: neomutt
base: core22
adopt-info: neomutt
summary: NeoMutt is a command line mail reader (or MUA)
description: |
  Command line mail reader based on Mutt, with added features.
 
  Neomutt supports all the features that are supported by Mutt, including
  `POP` and `IMAP` support, `SSL` encryption and `SASL` authentication,
  threading and `GPG` support.
 
  In addition, the neomutt snap provides:
  * Notmuch: a mail indexing tools that provides advanced features such as
    full-text search, thread reconstruction and added features.
  * Color attachment headers using regex, just like mail bodies.
  * Custom rules for theming the mail index.
  * NNTP support.
  * Visual progress bar for slow operations.
  * Trash folder.
  * Google's `oauth2.py` script (https://github.com/google/gmail-oauth2-tools), see
    https://neomutt.org/guide/optionalfeatures#6-%C2%A0oauthbearer-and-xoauth2-support
    for usage details.
  * Text-based Web browsers:
    * `w3m`
    * `lynx`
    * `links`
    * `links2`
    * `elinks`
  * Utilities:
    * `urlview`
    * `urlscan`
  * Editors:
    * `vim`
    * `nvim`

  The snap version of neomutt expects configuration files in

      ~/snap/neomutt/current

  The main configuration file, for example, has to be placed in

      ~/snap/neomutt/current/.neomuttrc

  Note that this directory is versioned and is backed up when the snap is
  removed (see https://snapcraft.io/docs/data-locations#heading--user).

  OAuth2 Support

  Follow the direction in
  https://neomutt.org/guide/optionalfeatures#6-%C2%A0oauthbearer-and-xoauth2-support
  or simply run

      neomutt.oauth2 --help

  to get instructions on how to create Client ID and Client Secrets. Create a
  refresh token,

      neomutt.oauth2 --generate_oauth2_token

  And add the following to the Neomutt configuration file,

      set imap_authenticators="oauthbearer"
      set imap_oauth_refresh_command="oauth2 --quiet \
        --user=[email_address] \
        --client_id=[client_id] \
        --client_secret=[client_secret] \
        --refresh_token=[refresh_token

  Note that within the Neomutt configuration file, the `oauth2` script can be
  called without specifying a path.
website: https://neomutt.org
contact: https://github.com/nicolasbock/neomutt-snap/issues
license: Apache-2.0
issues: https://github.com/nicolasbock/neomutt-snap/issues
source-code: https://github.com/nicolasbock/neomutt-snap
grade: stable
confinement: strict

apps:
  neomutt:
    command: usr/bin/neomutt
    plugs:
      - home
      - locale-control
      - network
  oauth2:
    command: bin/oauth2
    plugs:
      - network

environment:
  LOCPATH: $SNAP/usr/lib/locale
  VIMRUNTIME: $SNAP/usr/share/vim/vim82

parts:
  neomutt:
    after: [neomutt-test-files, neomutt-support]
    plugin: dump
    source: https://github.com/neomutt/neomutt.git
    source-branch: main
    # source-branch: devel/fmemopen
    build-packages:
      - docbook-simple
      - docbook-xsl
      - execstack
      - file
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme-dev
      - libgss-dev
      - libidn-dev
      - libkrb5-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.4-dev
      - liblz4-dev
      - libncurses-dev
      - libnotmuch-dev
      - libqdbm-dev
      - on amd64:
        - librocksdb-dev
      - libsasl2-dev
      - libssl-dev
      - libtdb-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - libzstd-dev
      - tcl
      - xsltproc
    override-pull: |
      set -e -u -x
      craftctl default
      craftctl set version="$(git describe)"
    override-build: |
      set -e -u -x
      declare -a HEADER_CACHES=(
        --bdb
        --gdbm
        --kyotocabinet
        --lmdb
        --qdbm
        --tdb
        --tokyocabinet
      )
      if dpkg -l librocksdb-dev; then
        HEADER_CACHES=( ${HEADER_CACHES[@]} --rocksdb )
      else
        HEADER_CACHES=( ${HEADER_CACHES[@]} --disable-rocksdb )
      fi
      ./configure \
        --testing \
        --gpgme \
        --gnutls \
        --gss \
        --sasl \
        --ssl \
        --lua \
        --notmuch \
        --mixmaster \
        --disable-idn \
        --idn2 \
        ${HEADER_CACHES[@]} \
        --lz4 \
        --zlib \
        --zstd \
        --full-doc \
        --prefix=/usr
      sed -i -e 's:\(SYSCONFDIR\) ".*":\1 "/snap/neomutt/current/etc":' config.h
      make
      NEOMUTT_TEST_DIR="$(readlink --canonicalize ${SNAPCRAFT_PART_BUILD}/../../neomutt-test-files/build)" \
        make test
      make install DESTDIR=${SNAPCRAFT_PART_INSTALL}
    override-prime: |
      set -e -u -x
      craftctl default
      # Clear execstack flag (only relevant on arm)
      readarray -t files < <(find ${CRAFT_PRIME}/usr/lib \
        \( -type f -a \! -type l \) \
        -exec execstack --query '{}' \; | grep -v '^-')
      for file in "${files[@]}"; do
        execstack --clear-execstack "$(echo ${file} | awk '{print $2}')"
      done
      sed --in-place \
        --expression 's:/usr/share/doc:${SNAP}/usr/share/doc:' \
        --expression 's:manual.txt:manual.html:' \
        --expression 's:less:w3m:' \
        ${CRAFT_PRIME}/etc/neomuttrc
    stage-packages:
      - libassuan0
      - libgdbm6
      - libgflags2.2
      - libgmime-3.0-0
      - libgpgme11
      - libidn12
      - libkyotocabinet16v5
      - liblmdb0
      - liblua5.4-0
      - liblz4-1
      - libnotmuch5
      - libqdbm14
      - on amd64:
        - librocksdb6.11
      - libsnappy1v5
      - libtalloc2
      - libtdb1
      - libtokyocabinet9
      - libxapian30
      - libzstd1
      - locales-all
  neomutt-support:
    plugin: nil
    stage-packages:
      - elinks
      - links
      - links2
      - lynx
      - manpages
      - neovim
      - nvi
      - sendmail
      - tnftp
      - urlscan
      - urlview
      - vim
      - w3m
    override-prime: |
      set -e -u -x
      craftctl default
      ln -sf vim.basic usr/bin/vim
      ln -sf vim.basic usr/bin/view
      ln -sf tnftp usr/bin/ftp
  neomutt-test-files:
    plugin: dump
    source: https://github.com/neomutt/neomutt-test-files.git
    source-commit: '34f79ee9d91863a97f6e18700aea51157b8610cf'
    override-build: |
      set -e -u -x
      export NEOMUTT_TEST_DIR="${SNAPCRAFT_PART_BUILD}/build"
      ./setup.sh
  google-oauth-scripts:
    after:
      - google-oauth-scripts-patches
    plugin: python
    source: https://github.com/google/gmail-oauth2-tools.git
    source-commit: 'e3229155a4037267ce40f1a3a681f53221aa4d8d'
    override-build: |
      set -e -u -x
      PATCHES=$(readlink --canonicalize ${SNAPCRAFT_PART_BUILD}/../../google-oauth-scripts-patches/build)
      for patch in ${PATCHES}/*.patch; do
        patch -p1 < ${patch}
      done
      install --mode 0755 -D -T \
        python/oauth2.py \
        ${SNAPCRAFT_PART_INSTALL}/bin/oauth2
    stage:
      - bin/oauth2
  google-oauth-scripts-patches:
    plugin: dump
    source: patches
    stage:
      - -./**
